import Web3 from 'web3';

// 1. Connect to local Ganache blockchain instance (Default RPC port is usually 7545 or 8545)
const web3 = new Web3('http://127.0.0.1:7545');

// 2. IMPORTANT: Replace this with your actual deployed contract address from Ganache/Remix
const CONTRACT_ADDRESS = '0xD37E851EC5de0F7347D4586d4731a4177281D2fc'; // <-- Update this!

// 3. The ABI from ThreatLog.sol
const CONTRACT_ABI = [
  {
    "anonymous": false,
    "inputs": [
      { "indexed": false, "internalType": "string", "name": "message", "type": "string" },
      { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }
    ],
    "name": "LogAdded",
    "type": "event"
  },
  {
    "inputs": [{ "internalType": "string", "name": "_message", "type": "string" }],
    "name": "addLog",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getLogs",
    "outputs": [
      {
        "components": [
          { "internalType": "string", "name": "message", "type": "string" },
          { "internalType": "uint256", "name": "timestamp", "type": "uint256" }
        ],
        "internalType": "struct ThreatLog.LogEntry[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
];

// Initialize the contract instance
const contract = new web3.eth.Contract(CONTRACT_ABI, CONTRACT_ADDRESS);

/**
 * Stores a new threat log on the blockchain.
 * @param {string} message - The threat alert message
 */
export const storeLog = async (message) => {
  try {
    // Get the list of accounts automatically generated by Ganache
    const accounts = await web3.eth.getAccounts();
    
    // Send a transaction to the smart contract using the first Ganache account
    const receipt = await contract.methods.addLog(message).send({
      from: accounts[0],
      gas: 3000000 // Gas limit for the transaction
    });
    
    console.log("Log successfully written to blockchain!", receipt.transactionHash);
    return receipt;
  } catch (error) {
    console.error("Error storing log on blockchain:", error);
    return null;
  }
};

/**
 * Retrieves all stored threat logs from the blockchain.
 */
export const getLogs = async () => {
  try {
    // .call() is used because getting data doesn't modify the blockchain or cost gas
    const logs = await contract.methods.getLogs().call();
    
    // Format the returned Web3 tuples into standard JavaScript objects
    const formattedLogs = logs.map(log => ({
      message: log.message,
      // Convert the Unix timestamp (BigInt string) to a standard integer
      timestamp: Number(log.timestamp) 
    }));
    
    return formattedLogs;
  } catch (error) {
    console.error("Error retrieving blockchain logs:", error);
    return [];
  }
};
